AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A starter AWS Lambda function.
Resources:
  GetFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: A starter AWS Lambda function.
      Runtime: python2.7
      Handler: lambda_function.lambda_handler
      CodeUri: ./src
      Policies: AmazonDynamoDBFullAccess
      MemorySize: 128
      Timeout: 3
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /resource/{resourceId}
            Method: get

  # PutFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Handler: index.put
  #     Runtime: nodejs6.10
  #     CodeUri: s3://<bucket>/api_backend.zip
  #     Policies: AmazonDynamoDBFullAccess
  #     Environment:
  #       Variables:
  #         TABLE_NAME: !Ref Table
  #     Events:
  #       PutResource:
  #         Type: Api
  #         Properties:
  #           Path: /resource/{resourceId}
  #           Method: put

  # DeleteFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Handler: index.delete
  #     Runtime: nodejs6.10
  #     CodeUri: s3://<bucket>/api_backend.zip
  #     Policies: AmazonDynamoDBFullAccess
  #     Environment:
  #       Variables:
  #         TABLE_NAME: !Ref Table
  #     Events:
  #       DeleteResource:
  #         Type: Api
  #         Properties:
  #           Path: /resource/{resourceId}
  #           Method: delete

  Table:
    Type: AWS::Serverless::SimpleTable
