AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A starter AWS Lambda function.
Resources:
  GetFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: A starter AWS Lambda function.
      Runtime: python2.7
      Handler: lambda_function.get
      CodeUri: ./src
      Policies: AmazonDynamoDBFullAccess
      MemorySize: 128
      Timeout: 3
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
          BASE_URL: 'http://jrw-psst-angular.s3-website-us-east-1.amazonaws.com'
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /resource/{resourceId}
            Method: get

  PostFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python2.7
      Handler: lambda_function.post
      CodeUri: ./src
      Policies: 
        - AmazonDynamoDBFullAccess
        - arn:aws:iam::445549561793:policy/LambdaSESSendEmail
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
          BASE_URL: 'http://jrw-psst-angular.s3-website-us-east-1.amazonaws.com'
      Events:
        PostResource:
          Type: Api
          Properties:
            Path: /resource
            Method: post

  DeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python2.7
      Handler: lambda_function.delete
      CodeUri: ./src
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
          BASE_URL: 'http://jrw-psst-angular.s3-website-us-east-1.amazonaws.com'
      Events:
        DeleteResource:
          Type: Api
          Properties:
            Path: /resource/{resourceId}
            Method: delete

  Table:
    Type: AWS::Serverless::SimpleTable
    PrimaryKey:
      Name: uuid
      Type: String
