AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A starter AWS Lambda function.
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: ./swagger.yaml
      StageName: Prod
      Variables:
        # NOTE: Before using this template, replace the <<region>> and <<account>> fields
        #       in Lambda integration URI in the swagger file to region and accountId 
        #       you are deploying to
        GetFunctionName: !Ref GetFunction
        PostFunctionName: !Ref PostFunction
        DeleteFunctionName: !Ref DeleteFunction


  GetFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: A starter AWS Lambda function.
      Runtime: python2.7
      Handler: lambda_function.get
      CodeUri: ./src
      Policies: AmazonDynamoDBFullAccess
      MemorySize: 128
      Timeout: 3
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
          BASE_URL: 'https://psst.dayspring-tech.net'
      Events:
        GetResource:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /resource/{resourceId}
            Method: get

  PostFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python2.7
      Handler: lambda_function.post
      CodeUri: ./src
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
          BASE_URL: 'https://psst.dayspring-tech.net'
      Events:
        PostResource:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /resource
            Method: post

  DeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python2.7
      Handler: lambda_function.delete
      CodeUri: ./src
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
          BASE_URL: 'https://psst.dayspring-tech.net'
      Events:
        DeleteResource:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /resource/{resourceId}
            Method: delete

  Table:
    Type: AWS::Serverless::SimpleTable
    PrimaryKey:
      Name: uuid
      Type: String

Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value: !Join
      - ''
      - - https://
        - !Ref ApiGatewayApi
        - '.execute-api.'
        - !Ref 'AWS::Region'
        - '.amazonaws.com/Prod'